export const TASKS_ACTIONS = {
  DELETE_TASK: "DELETE_TASK",
  ADD_TASK: "ADD_TASK",
  TOGGLE_TASK: "TOGGLE_TASK",
  CHANGE_FILTER: "CHANGE_FILTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ADD_DESCRIPTION: "ADD_DESCRIPTION",
};

export const FILTER_STATUSES = {
  ALL: "All",
  DONE: "Done",
  ACTIVE: "Active",
};
